### ISSUE TITLE
Fishing mode not auto-activated after combat

### ISSUE THREAD

**Issue by IvikN** [Phanx/GoFish#2] opened 2016-11-01 11:25 UTC
Can you please add In combat fishing so this addon wouldn't turns itself off every time I'm in combat. I even created a macro to switch it on but its all so frustrating that every time I aggro some spawned mob around fishing spots I need to press it (cause hovering over pools isn't working in 50% of the time)

**Comment by Phanx** [comment] 2016-11-03 07:53
Not possible, due to Blizzard restrictions on spell casting (fishing is a spell cast).

The way double-click fishing works is that the first right-click on the game world shows an invisible action button over the entire screen. The action button has a macro assigned to it (just like dragging a macro onto one of the buttons on your regular action bar). The second right-click doesn't hit the game world at all -- it hits the action button, which runs the macro, which casts Fishing and hides the button, allowing further clicks to hit the game world again.

Clicking on the game world can't be used to hide or show a secure frame (the action button) in combat, because it's not an actual key/mouse binding. **Actually binding** the right mouse button to show the "click anywhere to fish" button would prevent any other use of the right mouse button -- you wouldn't be able to interact with NPCs by right-clicking them, or right-click on unit frames to get a menu, for example -- including clicking on the "click to fish" button. (You'd have to right-click, then left-click, instead of just double-right-clicking.) Obviously this would not be a very useful setup!

---

If hovering over pools is failing to activate fishing mode **outside of combat**, please let me know which types of pools are involved (eg. "Highmountain Salmon School") and which language you're playing WoW in. If you're not playing in English, please provide both the English and localized name of the fishing pool; most likely, the translation is simply missing for your language.

**Comment by IvikN** [comment] 2016-11-03 08:08
Ah. That's how it works, okay then. But still though I would like to do something else instead of constantly hitting macro.
Pools that don't work - most of the new pools from Legion (I don't fish in old pools though and don't know if they work) also those world quest pools that contain only one fish seem don't work at all.
They work fine when you out of combat for too long and hover over them first time. Then if you go in combat and then out - hovering stops working for like 10-15 minutes or for complete random time. 
I'm playing English version (EU) of WoW.

**Comment by Phanx** [comment] 2016-11-03 08:43
> if you go in combat and then out - hovering stops working
> for like 10-15 minutes or for complete random time.

Do you have any error display addon (Bugger, BugSack, Swatter) running? 
If not, can you install one? Entering combat doesn't set some kind of 
timeout -- the addon checks for combat (among other things) **every 
time** you hover over a fish pool -- so based on your description, it 
sounds like something else is happening.

Here's the full list of things that will prevent hovering from 
activating fishing mode:
- Mounted
- In combat
- In a pet battle
- In a vehicle
- Dead or ghost
- In a shapeshift form (other than rogue stealth or druid moonkin)
- Channeling a far sight ability

> Pools that don't work - most of the new pools from Legion (I don't
> fish in old pools though and don't know if they work) also those world
> quest pools that contain only one fish seem don't work at all.

All of the English names for normal Legion fish pools were added in 
version 7.0.3.0, which was released on July 26th. Double-check that 
you're up to date.

For the world quest pools, I've added a few for the upcoming 7.1 
release, which I'm about to push to Curse and WoWI. If you still notice 
any missing after that, please open a new ticket with their names so I 
can add them to the list.

**Comment by IvikN** [comment] 2016-11-03 09:28
Well I'm not doing anything. I'm just going out of combat and trying to hover over pools and **gofish** isn't going "online", I'm waiting a little bit longer and when still there is no action from gofish I'm hitting macro /gofish for turn it on. Maybe there is some kind of timer after combat ends that makes gofish off? I don't know some kind of after-after combat (echo?) (lul).
Oh well I have last version from Curse and will try to look at it more closely. I do have a Swatter, but there is no errors to pop up or look at.

**Comment by Phanx** [comment] 2016-11-03 11:07
> Maybe there is some kind of timer after combat ends that makes gofish 
> off?

Nope. The only timer is the one that turns off "click to fish" mode 
after X seconds of no hovering and no fishing if "click to fish" mode 
was activated by hovering. (And you should see the notification in chat 
when that happens.)

The only other thing I can think of is that if the mouse is already over 
a fish pool when you exit combat, that doesn't trigger a hover check -- 
you need to move the mouse away, then back over the pool.

If you don't use a tooltip addon that disables the "fade out" effect on 
the tooltip, you have to wait until the tooltip has completely faded out 
before moving the mouse back over the fish pool. Otherwise, the game 
doesn't notify addons that the tooltip was shown again. For items (and 
quests, and units, and other things with unique identifiers) the game 
does notify addons that the tooltip was instructed to show that item, 
even if it was already showing the same thing, but world objects like 
mailboxes and fish pools don't have unique identifiers, so addons have 
to rely on the generic "the tooltip was hidden but now it's shown, or 
the tooltip was showing X but now it's showing Y" notification.

**Comment by IvikN** [comment] 2016-11-03 13:33
Checked right now. Its still as it is.
If I'm going out from combat gofish doesn't work for me no matter how many times I'm hovering over any pools in Legion. It's just not turns ON. If I'm going from "fresh" state (being without combat for 10+ minutes) it is turns ON at hover over any pool.

**Comment by Phanx** [comment] 2016-11-03 14:17
1. Update to 7.1.0.0 (released about 2 hours ago) if you haven't already.
2. Replace the Addon.lua file in your GoFish folder with this one:
   https://gist.github.com/Phanx/008e2d07ab66fb40ba5eb9a07c808c41
3. Reload your UI.
4. Try to reproduce the problem.

When you mouse over **anything**, you'll see a chat frame message indicating whether or not it's recognized as a fish pool. If it is, but fishing mode isn't successfully activated, you'll see another message giving the reason. If you see no messages at all, and Swatter still isn't reporting any errors, try without other addons. If you still see no messages or errors, there is something seriously wrong with your WoW installation; try exiting the game and deleting your Cache folder, and/or running the repair tool in the Battle.net desktop app.

**Comment by IvikN** [comment] 2016-11-03 20:12
Ah. its says "shapeshifted" cause of rogue stealth I think. that's why it didn't work. 
Can you please add some kind of check marks in settings of your addon to turn it on while stealthed/mounted? 
Although if not I fully understand how it works now. its not very complicated but still would be cool to get it ON without doing additional tapping or clicking (going out of stealth/dismounting

Also sorry for misinformation, didn't know what could be a problem. Should include that I'm playing rogue and immediately going in stealth after combat ends.

**Comment by Phanx** [comment] 2016-11-04 15:44
Rogue stealth already has an exception, along with moonkin for druids, but it's possible Blizzard changed the form ID. What do you get if you run this command while in stealth:

/dump GetShapeshiftForm(true)

**Comment by IvikN** [comment] 2016-11-05 17:22
still saying "shapeshifted" 
AH and it says [1]=1 if it is information you seek.

**Comment by armordecai** [comment] 2017-09-16 10:49
Fixed

**Closed as completed by armordecai** 2017-09-16 10:49 UTC
